development:
  adapter: postgresql
  encoding: UTF-8
  database: simple_pet_records_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: UTF-8
  database: simple_pet_records_test
  pool: 5
  host: localhost


production:
  adapter: postgresql
  encoding: UTF-8
  database: simple_pet_records_production
  pool: 5